CREATE OR REPLACE TRIGGER CUSTOMERACCOUNTTR 
BEFORE INSERT ON CUSTOMER_ACCOUNTS 
FOR EACH ROW 
WHEN (new.ACCOUNT_ID IS NULL) 
BEGIN
  SELECT CUSTSEQ.NEXTVAL
  INTO :new.ACCOUNT_ID
  FROM Dual;
END;
/
