CREATE OR REPLACE TRIGGER CUST_ACC_TR 
BEFORE INSERT ON CUSTOMER_ACCOUNTS 
REFERENCING OLD AS OLDID NEW AS NEWID 
FOR EACH ROW 
WHEN (NEW.ACC_ID IS NULL) 
BEGIN
  SELECT CUST_ACC_SEQ.NEXTVAL
  INTO : NEW.ACC_ID
  FROM dual;
END;
/
